[build]
builder = "nixpacks"

[deploy]
startCommand = "python taskflow/manage.py migrate && python taskflow/manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT --workers 3 taskflow.wsgi"
healthcheckPath = "/"